<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGB3PoN4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGB3PoN4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGB3PoN4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGB3PoN4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGB3PoN4\App_KernelDevDebugContainer([
    'container.build_hash' => 'GB3PoN4',
    'container.build_id' => '66750e31',
    'container.build_time' => 1696196167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGB3PoN4');
